### ISSUE TITLE
Counter is 1 off

### ISSUE THREAD

**Issue by e2o** [stursby/hasvuepassedreactyet#1]
![image](https://user-images.githubusercontent.com/6171742/41456765-c24347ae-7081-11e8-8cf2-69c40f415fe2.png)

The title clearly says "Has Vue **passed** React yet", so the "x stars away" counter should be increased by 1, as leveling is not the same as passing.

**Comment by skrln** [comment]
This is a critical bug. Needs urgent fix!

**Comment by e2o** [comment]
Opened a pull request to resolve the issue: https://github.com/stursby/hasvuepassedreactyet/pull/2
