### ISSUE TITLE
Does not work in iOS Safari 10.3

### ISSUE THREAD

**Issue by fortytw2** [stursby/hasvuepassedreactyet#12]
^ See title, pretty self-explanatory, probably need to configure `babel-polyfill`

**Comment by stursby** [comment]
Hmmm, I'm on Safari 11 so can't test on a real device, but BrowserStack looks good. (iPhone 7 Plus iOS 10.3)

![image](https://user-images.githubusercontent.com/527849/41485814-a5d26214-70a7-11e8-9f79-0560ae757194.png)

**Comment by fortytw2** [comment]
Sure looks like it works for me, too. Didn't when I wrote this 🤔
