### ISSUE TITLE
Opt-in auto fetch feature

### ISSUE THREAD

**Issue by palashmon** [stursby/hasvuepassedreactyet#14]
Hi, first of all thanks for this awesome project.

I would like to request a feature which can be opt-in which will auto-fetch the GitHub stars and update the UI after maybe after each 20-30 secs delay. Maybe we can provide a checkbox for those who might want to keep a tab open and check occasionally what the current status without clicking anything.

Maybe we can just call `fetchRepos`/`reload` functions inside a `setInterval`.

Regards!

**Comment by stursby** [comment]
Yea, you could have a checkbox or something that would opt-in for auto reloading, however, I doubt people would leave the page open for minutes, ha! I feel like the "click to reload" is a good middle ground. Going to close for now, but feel free to submit a PR if you'd like to explore this more.
