### ISSUE TITLE
"API rate limit exceeded" but stills Loading state

### ISSUE THREAD

**Issue by HZooly** [stursby/hasvuepassedreactyet#5]
Request to `/fetchGithubStarts` send back a 200 HTTP code, but without data:

```{"data":null,"errors":[{"message":"API rate limit exceeded","type":"RATE_LIMITED"}]}```

"Loading..." indicator stills displayed.

**Comment by Zomis** [comment]
Seems to work again now. For how long? Who knows :)

**Comment by nkoehring** [comment]
Rate limits are per hour.

**Comment by HZooly** [comment]
Yes, Github API without being authenticated is limited to 60rph

https://developer.github.com/changes/2012-10-14-rate-limit-changes/

Thanks @nkoehring for your PR.
