### ISSUE TITLE
Can't view without javascript

### ISSUE THREAD

**Issue by moonshadow565** [stursby/hasvuepassedreactyet#6]
The website can not be viewed without javascript.
I don't think javascript is needed for full functionality?
![image](https://user-images.githubusercontent.com/7480230/41464910-4898b3ba-709c-11e8-8960-c1c72d74fe46.png)

**Comment by nkoehring** [comment]
Javascript is absolutely needed for full functionality. This page uses GraphQL requests to the Github API to check the amount of stars of the respective repositories. The only way to do this without JavaScript would be with a backend. But this page is about frameworks commonly used for Single Page Javascript Applications. But lets not feed the trolls too much here.

**Comment by pickfire** [comment]
T_T

![2018-06-15-214908_564x340_scrot](https://user-images.githubusercontent.com/4687791/41471333-eb09028c-70e5-11e8-9384-3936c7b202f4.png)
