### ISSUE TITLE
SITE FREEZES | API Calls Exceeded

### ISSUE THREAD

**Issue by IamManchanda** [stursby/hasvuepassedreactyet#8]
<img width="332" alt="screen shot 2018-06-15 at 4 34 40 pm" src="https://user-images.githubusercontent.com/4970624/41465116-5448a6a2-70ba-11e8-8fd1-aa114d8bace2.png">

---

![api-calls](https://user-images.githubusercontent.com/4970624/41465126-62825902-70ba-11e8-940f-eb9f98f5cdbd.jpg)

**Comment by nkoehring** [comment]
@IamManchanda it helps to check for existing issues. #5 for example.

**Comment by IamManchanda** [comment]
ohk closing it!
